name: Update Credly Badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: lorraine-ferrusi
          DEBUG: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: data-adventurer/data-adventurer
          COMMIT_MESSAGE: Updated README with new badges
          CREDLY_SORT: RECENT
          BADGE_SIZE: 110
          NUMBER_LAST_BADGES: 5
          GH_API_URL: https://api.github.com
